pluginManagement {
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '2.3.0'
    }
}
rootProject.name = 'carbontrack-microservices'
include(
        'api-gateway',
        'discovery-server',
        'auth-service',
        'user-service',
        'activity-service',
        'ai-service',
        'common-library'
)
