spring.application.name=CarbonTrack Backend

spring.datasource.url=jdbc:oracle:thin:@host.docker.internal:1521:oracle
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000
spring.jpa.properties.hibernate.jdbc.batch_size=30

# Log file location
logging.file.name=logs/carbontrack-backend.log

# Log levels
logging.level.root=INFO
logging.level.com.carbontrack=DEBUG

spring.cloud.session.jdbc.enabled=false

eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.enabled=false
spring.cloud.discovery.enabled=false
# Pattern for log messages

spring.profiles.active=dev

server.port=8080
jwt.secret=myTopSecretKeyIsInPradhikaran_Nigdi_PuneAndIskeptAtVeryHiddenPlace123