server.port=8082
spring.application.name=user-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
#your_username
spring.datasource.password=${DB_PASSWORD}
#your_password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Feign Client Configuration
activity-service.url=http://localhost:8083

management.endpoints.web.exposure.include=health,info

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha


spring.kafka.bootstrap-servers=localhost:9092

# consumer config (JSON)
spring.kafka.consumer.group-id=user-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# allow deserialization for event classes
spring.kafka.consumer.properties.spring.json.trusted.packages=*