server.port=8080
spring.application.name=api-gateway-service

# =====================
# EUREKA
# =====================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =====================
# GATEWAY ROUTES
# =====================

# AUTH (PUBLIC)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# USER (SECURED)
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/users/**
#spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilterFactory

# ACTIVITY (SECURED)
spring.cloud.gateway.routes[2].id=activity-service
spring.cloud.gateway.routes[2].uri=lb://ACTIVITY-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/activities/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthenticationFilterFactory

# AI (SECURED)
spring.cloud.gateway.routes[3].id=ai-service
spring.cloud.gateway.routes[3].uri=lb://AI-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/ai/**
spring.cloud.gateway.routes[3].filters[0]=JwtAuthenticationFilterFactory

# =====================
# ACTUATOR
# =====================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# =====================
# OPTIONAL SAFETY
# =====================
spring.cloud.gateway.discovery.locator.enabled=false

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

spring.threads.virtual.enabled=true