spring.application.name=CarbonTrack Backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
#your_username
spring.datasource.password=${DB_PASSWORD}
#your_password
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.threads.virtual.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000
spring.jpa.properties.hibernate.jdbc.batch_size=30

# Log file location
logging.file.name=logs/carbontrack-backend.log

# Log levels
logging.level.root=ERROR
logging.level.com.carbontrack=DEBUG

# Pattern for log messages


spring.profiles.active=prod

management.server.port=8081
management.endpoints.web.base-path=/


server.port=8080
server.tomcat.threads.max=200
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

management.endpoints.web.exposure.include=health,metrics,prometheus

eureka.client.service-url.defaultZone=http://host.docker.internal:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.enabled=false
spring.cloud.discovery.enabled=false

spring.cloud.session.jdbc.enabled=false
spring.session.jdbc.initialize-schema=never
spring.session.store-type=jdbc

spring.docker.compose.enabled=false

spring.ai.openai.api-key=${OPENAI_API_KEY:dummy-key}
#spring.ai.openai.model=gpt-4o-mini
spring.ai.openai.model=gpt-3.5-turbo
openai.api.url=https://api.openai.com/v1/chat/completions
#openai.api.url=https://api.openai.com/v1/responses